/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.tsx",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/screens/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'sf-display': ['"SF Pro Display"', 'sans-serif'],
        'sf-text': ['"SF Pro Text"', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      colors: {
        primary: "#091249",
        secondary: "#A1A1A1",
        black: "#000000",
        white: "#FFFFFF",
        green: "#1EB835",
        orange: "#F75C31",
        pink: "#E02BB9",
        red: "#F30B26",
        greenLight: "#BCEAC2",
        orangeLight: "#FDCEC1",
        pinkLight: "#F6BFEA",
        redLight: "#FBB6BE",
        purpleLight: "#D7C1FD",
        gray900: "#353535",
        gray800: "#484848",
        gray700: "#606060",
        gray600: "#808080",
        gray500: "#A1A1A1",
        gray400: "#C5C5C5",
        gray300: "#E1E1E1",
        gray200: "#ECECEC",
        gray100: "#F5F5F5",
        transparent: "transparent",
      },
      fontSize: {
        display: ['34px', '41px'],
        'display-bold': ['34px', '41px'],
        h1: ['30px', '36px'],
        'h1-bold': ['28px', '36px'],
        h2: ['26px', '31px'],
        'h2-bold': ['24px', '31px'],
        h3: ['23px', '26px'],
        'h3-bold': ['20px', '26px'],
        h4: ['18px', '21px'],
        'h4-semibold': ['16px', '21px'],
        h5: ['16px', '18px'],
        'h5-semibold': ['14px', '18px'],
        body: ['18px', '20px'],
        'body-medium': ['14px', '20px'],
        footnote: ['15px', '20px'],
        'footnote-medium': ['13px', '20px'],
        captionL: ['12px', '17px'],
        'captionL-semibold': ['12px', '17px'],
        captionM: ['11px', '15px'],
        'captionM-semibold': ['11px', '15px'],
        captionS: ['10px', '14px'],
        'captionS-bold': ['10px', '14px'],
      },
    },
  },
  plugins: [],
}
